llm:
  provider: OPENROUTER              # Используем OpenRouter как LLM-провайдера

  meta:
    model: tngtech/deepseek-r1t2-chimera:free  # Бесплатная модель через OpenRouter
    max_tokens: 15000              # Максимальное количество токенов в ответе
    temperature: 0.3               # Чем ниже значение, тем строже ответы

  http_client:
    timeout: 120
    api_url: https://openrouter.ai/api/v1      # Базовый URL API

vcs:
  provider: GITHUB                # Используем GitHub как систему контроля версий

  http_client:
    timeout: 120
    api_url: https://api.github.com            # API GitHub
